// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj0MPmPqEViMKrPgvE4SuiYYROcLXCw6o',
    appId: '1:739679113447:web:5dc424c931a39851925242',
    messagingSenderId: '739679113447',
    projectId: 'cs-study-buddy-4e7ef',
    authDomain: 'cs-study-buddy-4e7ef.firebaseapp.com',
    storageBucket: 'cs-study-buddy-4e7ef.firebasestorage.app',
    measurementId: 'G-JXQSLJL4H1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL3PnDAtCbPVPd9JKXG5Dye4qksBSvU8s',
    appId: '1:739679113447:android:fe0a0eae3260f218925242',
    messagingSenderId: '739679113447',
    projectId: 'cs-study-buddy-4e7ef',
    storageBucket: 'cs-study-buddy-4e7ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ3t4tTYZWLhDOxpBy_cpEg0UpToMGXjE',
    appId: '1:739679113447:ios:8252c3280dd6de6b925242',
    messagingSenderId: '739679113447',
    projectId: 'cs-study-buddy-4e7ef',
    storageBucket: 'cs-study-buddy-4e7ef.firebasestorage.app',
    iosBundleId: 'com.example.csStudyBuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJ3t4tTYZWLhDOxpBy_cpEg0UpToMGXjE',
    appId: '1:739679113447:ios:8252c3280dd6de6b925242',
    messagingSenderId: '739679113447',
    projectId: 'cs-study-buddy-4e7ef',
    storageBucket: 'cs-study-buddy-4e7ef.firebasestorage.app',
    iosBundleId: 'com.example.csStudyBuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCj0MPmPqEViMKrPgvE4SuiYYROcLXCw6o',
    appId: '1:739679113447:web:25ffd3b20bca813d925242',
    messagingSenderId: '739679113447',
    projectId: 'cs-study-buddy-4e7ef',
    authDomain: 'cs-study-buddy-4e7ef.firebaseapp.com',
    storageBucket: 'cs-study-buddy-4e7ef.firebasestorage.app',
    measurementId: 'G-JRQTPWM70P',
  );
}
